export const CATEGORIES = [
  "Permits To Work",
  "PPE",
  "Housekeeping",
  "Environmental Compliance",
  "Facilities Inspection",
  "Cranes And Lifting Operations",
  "General Site Safety",
  "Site Supervision Compliance",
  "Laydown Safety Compliance",
  "Chemical Handling/Storage",
  "Excavations",
  "Fire Prevention/Protection And Hot Works",
  "Traffic Safety Management",
  "Marine",
  "Confined Spaces",
  "Fall Protection/Prevention Machine",
  "Hand/Power Tools & Machine",
  "Scaffolds & Ladders",
  "Vehicles And Mobile Heavy",
  "Electrical Compliance Equipment",
];

export const SHORT_CATS = [
  "Permits",
  "PPE",
  "Housekeep",
  "Env Comp",
  "Facilities",
  "Cranes",
  "Gen Safety",
  "Supervision",
  "Laydown",
  "Chemical",
  "Excavation",
  "Fire Prev",
  "Traffic",
  "Marine",
  "Confined",
  "Fall Prot",
  "Hand/Power",
  "Scaffolds",
  "Vehicles",
  "Electrical",
];

export const SCORE_KEYS = [
  "permits_to_work",
  "ppe",
  "housekeeping",
  "environmental_compliance",
  "facilities_inspection",
  "cranes_and_lifting",
  "general_site_safety",
  "site_supervision",
  "laydown_safety",
  "chemical_handling",
  "excavations",
  "fire_prevention",
  "traffic_safety",
  "marine",
  "confined_spaces",
  "fall_protection",
  "hand_power_tools",
  "scaffolds_ladders",
  "vehicles_mobile_heavy",
  "electrical_compliance",
];
